# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaguemains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguemainsuser',
            name='nickname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='leaguemainsuser',
            name='language',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='leaguemainsuser',
            name='region',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='leaguemainsuser',
            name='summoner',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
