# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 03:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('pk_block_id', models.AutoField(primary_key=True, serialize=False)),
                ('recmath', models.BooleanField()),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BlockItem',
            fields=[
                ('pk_blockitem_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('count', models.IntegerField()),
                ('fk_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='riotapi_static.Block')),
            ],
        ),
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('blurb', models.TextField()),
                ('pk_id', models.IntegerField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100)),
                ('lore', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('partype', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ChampionAllyTip',
            fields=[
                ('pk_championallytip_id', models.AutoField(primary_key=True, serialize=False)),
                ('championallytip', models.TextField()),
                ('fk_champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allytips', to='riotapi_static.Champion')),
            ],
        ),
        migrations.CreateModel(
            name='ChampionEnemyTip',
            fields=[
                ('pk_championenemytip_id', models.AutoField(primary_key=True, serialize=False)),
                ('championenemytip', models.TextField()),
                ('fk_champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enemytips', to='riotapi_static.Champion')),
            ],
        ),
        migrations.CreateModel(
            name='ChampionSpell',
            fields=[
                ('pk_championspell_id', models.AutoField(primary_key=True, serialize=False)),
                ('cooldownburn', models.CharField(max_length=20)),
                ('costburn', models.CharField(max_length=20)),
                ('costtype', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('key', models.CharField(max_length=100)),
                ('maxrank', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('isranged', models.BooleanField()),
                ('rangeburn', models.CharField(max_length=20)),
                ('resource', models.CharField(max_length=100)),
                ('sanitizeddescription', models.TextField()),
                ('sanitizedtooltip', models.TextField()),
                ('tooltip', models.TextField()),
                ('fk_champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spells', to='riotapi_static.Champion')),
            ],
        ),
        migrations.CreateModel(
            name='ChampionSpellCooldown',
            fields=[
                ('pk_championspellcooldown_id', models.AutoField(primary_key=True, serialize=False)),
                ('championspellcooldown', models.DecimalField(decimal_places=6, max_digits=10)),
                ('fk_championspell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooldown', to='riotapi_static.ChampionSpell')),
            ],
        ),
        migrations.CreateModel(
            name='ChampionSpellCost',
            fields=[
                ('pk_championspellcost_id', models.AutoField(primary_key=True, serialize=False)),
                ('championspellcost', models.IntegerField()),
                ('fk_championspell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost', to='riotapi_static.ChampionSpell')),
            ],
        ),
        migrations.CreateModel(
            name='ChampionSpellEffectA',
            fields=[
                ('pk_championspelleffects_a_id', models.AutoField(primary_key=True, serialize=False)),
                ('championspelleffect_a', models.DecimalField(decimal_places=6, max_digits=12, null=True)),
                ('fk_championspell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effect', to='riotapi_static.ChampionSpell')),
            ],
        ),
        migrations.CreateModel(
            name='ChampionSpellEffectB',
            fields=[
                ('pk_championspelleffects_b_id', models.AutoField(primary_key=True, serialize=False)),
                ('championspelleffect_b', models.DecimalField(decimal_places=6, max_digits=12)),
                ('fk_championspelleffect_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additonal_championspelleffects', to='riotapi_static.ChampionSpellEffectA')),
            ],
        ),
        migrations.CreateModel(
            name='ChampionSpellEffectBurn',
            fields=[
                ('pk_championspelleffectburn_id', models.AutoField(primary_key=True, serialize=False)),
                ('championspelleffectburn', models.CharField(max_length=20)),
                ('fk_championspell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effectBurn', to='riotapi_static.ChampionSpell')),
            ],
        ),
        migrations.CreateModel(
            name='ChampionSpellRange',
            fields=[
                ('pk_championspellrange_id', models.AutoField(primary_key=True, serialize=False)),
                ('championspellrange', models.IntegerField()),
                ('fk_championspell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='range', to='riotapi_static.ChampionSpell')),
            ],
        ),
        migrations.CreateModel(
            name='ChampionStats',
            fields=[
                ('pk_championstats_id', models.AutoField(primary_key=True, serialize=False)),
                ('armor', models.DecimalField(decimal_places=6, max_digits=10)),
                ('armorperlevel', models.DecimalField(decimal_places=6, max_digits=10)),
                ('attackdamage', models.DecimalField(decimal_places=6, max_digits=10)),
                ('attackdamageperlevel', models.DecimalField(decimal_places=6, max_digits=10)),
                ('attackrange', models.DecimalField(decimal_places=6, max_digits=10)),
                ('attackspeedoffset', models.DecimalField(decimal_places=6, max_digits=10)),
                ('attackspeedperlevel', models.DecimalField(decimal_places=6, max_digits=10)),
                ('crit', models.DecimalField(decimal_places=6, max_digits=10)),
                ('hp', models.DecimalField(decimal_places=6, max_digits=10)),
                ('hpperlevel', models.DecimalField(decimal_places=6, max_digits=10)),
                ('hpregen', models.DecimalField(decimal_places=6, max_digits=10)),
                ('hpregenperlevel', models.DecimalField(decimal_places=6, max_digits=10)),
                ('movespeed', models.DecimalField(decimal_places=6, max_digits=10)),
                ('mp', models.DecimalField(decimal_places=6, max_digits=10)),
                ('mpperlevel', models.DecimalField(decimal_places=6, max_digits=10)),
                ('mpregen', models.DecimalField(decimal_places=6, max_digits=10)),
                ('mpregenperlevel', models.DecimalField(decimal_places=6, max_digits=10)),
                ('spellblock', models.DecimalField(decimal_places=6, max_digits=10)),
                ('spellblockperlevel', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ChampionTag',
            fields=[
                ('pk_championtag_id', models.AutoField(primary_key=True, serialize=False)),
                ('championtag', models.CharField(max_length=100)),
                ('fk_champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='riotapi_static.Champion')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('pk_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('full', models.CharField(max_length=100, null=True)),
                ('group', models.CharField(max_length=100, null=True)),
                ('h', models.IntegerField(null=True)),
                ('sprite', models.CharField(max_length=100, null=True)),
                ('w', models.IntegerField(null=True)),
                ('x', models.IntegerField(null=True)),
                ('y', models.IntegerField(null=True)),
                ('path', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('pk_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('magic', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LevelTipEffect',
            fields=[
                ('pk_leveltipeffects_id', models.AutoField(primary_key=True, serialize=False)),
                ('leveltipeffect', models.TextField()),
                ('fk_championspell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leveltip_effect', to='riotapi_static.ChampionSpell')),
            ],
        ),
        migrations.CreateModel(
            name='LevelTipLabel',
            fields=[
                ('pk_leveltiplabels_id', models.AutoField(primary_key=True, serialize=False)),
                ('leveltiplabel', models.TextField()),
                ('fk_championspell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leveltip_label', to='riotapi_static.ChampionSpell')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleVersions',
            fields=[
                ('pk_module_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Passive',
            fields=[
                ('pk_passive_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('sanitizeddescription', models.TextField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riotapi_static.Image')),
            ],
        ),
        migrations.CreateModel(
            name='PatchVersions',
            fields=[
                ('pk_patch_id', models.AutoField(primary_key=True, serialize=False)),
                ('patch_version', models.CharField(max_length=20)),
                ('patch_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recommended',
            fields=[
                ('pk_recommended_id', models.AutoField(primary_key=True, serialize=False)),
                ('champion', models.CharField(max_length=100)),
                ('map', models.CharField(max_length=100)),
                ('mode', models.CharField(max_length=100)),
                ('priority', models.BooleanField()),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('fk_champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended', to='riotapi_static.Champion')),
            ],
        ),
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('pk_skin_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('num', models.IntegerField()),
                ('fk_champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skins', to='riotapi_static.Champion')),
                ('loading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loading', to='riotapi_static.Image')),
                ('splash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splash', to='riotapi_static.Image')),
            ],
        ),
        migrations.CreateModel(
            name='SpellVars',
            fields=[
                ('pk_spellvars_id', models.AutoField(primary_key=True, serialize=False)),
                ('dyn', models.CharField(max_length=20)),
                ('key', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=20)),
                ('rankswith', models.CharField(max_length=20)),
                ('fk_championspell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vars', to='riotapi_static.ChampionSpell')),
            ],
        ),
        migrations.CreateModel(
            name='SpellVarsCoeff',
            fields=[
                ('pk_spellvarscoeff_id', models.AutoField(primary_key=True, serialize=False)),
                ('coeff', models.DecimalField(decimal_places=6, max_digits=10)),
                ('fk_spellvars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coeff', to='riotapi_static.SpellVars')),
            ],
        ),
        migrations.AddField(
            model_name='moduleversions',
            name='module_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riotapi_static.PatchVersions'),
        ),
        migrations.AddField(
            model_name='championspell',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riotapi_static.Image'),
        ),
        migrations.AddField(
            model_name='champion',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='riotapi_static.Image'),
        ),
        migrations.AddField(
            model_name='champion',
            name='info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='riotapi_static.Info'),
        ),
        migrations.AddField(
            model_name='champion',
            name='passive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='riotapi_static.Passive'),
        ),
        migrations.AddField(
            model_name='champion',
            name='stats',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='riotapi_static.ChampionStats'),
        ),
        migrations.AddField(
            model_name='block',
            name='fk_recommended',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='riotapi_static.Recommended'),
        ),
    ]
